name: "GPT Code Review (TS)"
description: "Push 이벤트로 동작하는 OpenAI 기반 코드 리뷰 액션"
inputs:
  openai-key:
    description: "OpenAI API Key"
    required: true
  repo-token:
    description: "GitHub Token"
    required: true
  model:
    description: "OpenAI 모델 (기본: gpt-3.5-turbo)"
    required: false
    default: "gpt-3.5-turbo"
  slack-webhook-url:
    description: "Slack Webhook URL (선택사항, 알림용)"
    required: false
runs:
  using: "node22"
  main: "action/index.js"
outputs:
  ai_response:
    description: "AI가 생성한 코드 리뷰 텍스트"